from BaseClasses import ItemClassification

ITEM_CLASSIFICATIONS = {
    "Cerulean Aura": ItemClassification.progression,
    "Crimson Aura": ItemClassification.progression,
    "Springheel Boots": ItemClassification.progression,
    "Spider Gloves": ItemClassification.progression,
    "Letter A": ItemClassification.filler,
    "Letter B": ItemClassification.filler,
    "Letter C": ItemClassification.filler,
    "Letter D": ItemClassification.filler,
    "Letter E": ItemClassification.progression_skip_balancing,
    "Letter F": ItemClassification.filler,
    "Letter G": ItemClassification.filler,
    "Letter H": ItemClassification.filler,
    "Letter I": ItemClassification.filler,
    "Letter J": ItemClassification.filler,
    "Letter K": ItemClassification.filler,
    "Letter L": ItemClassification.filler,
    "Letter M": ItemClassification.filler,
    "Letter N": ItemClassification.filler,
    "Letter O": ItemClassification.filler,
    "Letter P": ItemClassification.progression_skip_balancing,
    "Letter Q": ItemClassification.filler,
    "Letter R": ItemClassification.progression_skip_balancing,
    "Letter S": ItemClassification.progression_skip_balancing,
    "Letter T": ItemClassification.filler,
    "Letter U": ItemClassification.progression_skip_balancing,
    "Letter V": ItemClassification.filler,
    "Letter W": ItemClassification.filler,
    "Letter X": ItemClassification.filler,
    "Letter Y": ItemClassification.filler,
    "Letter Z": ItemClassification.filler,
    "Lose The Game": ItemClassification.trap,
    "Stop Jumping Trap": ItemClassification.trap,
    "Secret Room Trap": ItemClassification.trap,
    "Left Spider Glove": ItemClassification.progression,
    "Right Spider Glove": ItemClassification.progression,
    "Unlock Teleporters": ItemClassification.progression,
    "Win the Game": ItemClassification.progression,
    "Nothing": ItemClassification.filler,
}