ITEM_IDS = {
    #1-30 are regular items.
    "Cerulean Aura": 1,
    "Crimson Aura": 2,
    "Springheel Boots": 3,
    "Spider Gloves": 4,
    "Letter A": 5,
    "Letter B": 6,
    "Letter C": 7,
    "Letter D": 8,
    "Letter E": 9,
    "Letter F": 10,
    "Letter G": 11,
    "Letter H": 12,
    "Letter I": 13,
    "Letter J": 14,
    "Letter K": 15,
    "Letter L": 16,
    "Letter M": 17,
    "Letter N": 18,
    "Letter O": 19,
    "Letter P": 20,
    "Letter Q": 21,
    "Letter R": 22,
    "Letter S": 23,
    "Letter T": 24,
    "Letter U": 25,
    "Letter V": 26,
    "Letter W": 27,
    "Letter X": 28,
    "Letter Y": 29,
    "Letter Z": 30,
    #31-40 is reserved for traps.
    "Lose The Game": 31,
    "Stop Jumping Trap": 32,
    "Secret Room Trap": 33,
    #other items.
    "Left Spider Glove": 41,
    "Right Spider Glove": 42,
    "Unlock Teleporters": 43,
    
    "Win The Game": 99,
    "Nothing": 100,
}