LOCATION_IDS = {
    # ID is equal to the treasure ID + 1.
    "Nice of You to Drop In": 1,
    "Secret Passage": 2,
    "Maps and Legends": 3,
    "Cerulean Aura": 4,
    "Mind the Gap": 5,
    "Avalon Calling": 6,
    "The Crab Cake Is a Lie": 7,
    "Yggdrasil": 8,
    "Covert Operators - Left": 9,
    "Covert Operators - Right": 10,
    "Aqueous Humor": 11,
    "Pit Stop": 12,
    "Like Ivy, Twisting": 13,
    "Hidden Crevasse": 14,
    "Hydra Is Myth": 15,
    "Artisan Stone Walls": 16,
    "Cave In": 17,
    "Obvious Movie Quote": 18,
    "Forgotten Tunnels - Left": 19,
    "Forgotten Tunnels - Right": 20,
    "The Coin and the Courage": 21,
    "Arcane Vocabulary - Top": 22,
    "Arcane Vocabulary - Bottom": 23,
    "Don't Be Hasty - Bottom": 24,
    "Don't Be Hasty - Top": 25,
    "Descent": 26,
    "Hardcore Prawn": 27,
    "You Have to Start the Game": 28,
    "Hops and Skips": 29,
    "Never Could See Any Other Way": 30,
    "Springheel Boots": 31,
    "The Arbitrarium": 32,
    "Playing with Fire": 33,
    "KISS Principle": 34,
    "Tower of Sorrows": 35,
    "Tower of Regrets": 36,
    "Snake, It's a Snake": 37,
    "Swimming Upstream": 38,
    "Subterranea": 39,
    "Contrived Lock/Key Mechanisms": 40,
    "Consolation Prize": 41,
    "Treasure Hunt": 42,
    "Bat Cave": 43,
    "Euclid Shrugged": 44,
    "Taking the Long Way - Left": 45,
    "Taking the Long Way - Right": 46,
    "Danger": 47,
    "Cognitive Resonance": 48,
    "Circular Logic": 49,
    "Leap of Faith": 50,
    "Precarious Footholds": 51,
    "Prawn Shot First": 52,
    "The Proper Motivation": 53,
    "Abandoned Alcove": 54,
    "Remnants of a Past Unknown": 55,
    "Attic Storeroom - Top": 56,
    "Attic Storeroom - Bottom": 57,
    "Vestibule": 58,
    "Shelter from the Storm": 59,
    "Uncertain Semiotics": 60,
    "Crimson Aura": 61,
    "Great Hall": 62,
    "An Even 0x80": 63,
    "The Floor Is Lava": 64,
    "Secret Cat Level - Left": 65,
    "Secret Cat Level - Right": 66,
    "Spider Gloves": 67,
    "Not Worth It!": 68,
    "Eponymous": 99
}