COORDS_TO_ROOM_NAME = {
    (-10, 2): "Slippery Slope - Room Entry",
    (-10, 3): "Nice of You to Drop In - Room Entry",

    (-9, 2): "Hollow King - Room Entry",
    (-9, 3): "Foot of the Throne - Room Entry",
    (-9, 4): "Welcome to the Underground - Room Entry",
    (-9, 5): "Long Way Down - Room Entry",
    (-9, 6): "Secret Passage - Room Entry",

    (-8, 1): "Maps and Legends - Room Entry",
    (-8, 2): "Cerulean Aura - Room Entry",
    (-8, 3): "Mind the Gap - Room Entry",
    (-8, 4): "Rock Transept - Room Entry",
    (-8, 5): "Avalon Calling - Room Entry",
    (-8, 6): "The Crab Cake Is a Lie - Room Entry",

    (-7, 1): "Yggdrasil - Room Entry",
    (-7, 2): "Covert Operators - Room Entry",
    (-7, 3): "I Wonder Where This Goes - Room Entry",
    (-7, 4): "Aqueous Humor - Room Entry",
    (-7, 5): "Et in Aether ego - Room Entry",
    (-7, 6): "Be Seeing You - Room Entry",

    (-6, 1): "The Grand Vault - Room Entry",
    (-6, 2): "The Quarry Hub - Room Entry",
    (-6, 3): "Pit Stop - Room Entry",
    (-6, 4): "Like Ivy, Twisting - Room Entry",
    (-6, 5): "It's More Scared of You - Room Entry",
    (-6, 6): "Hidden Crevasse - Room Entry",

    (-5, -3): "A Sickly Silver Moon - Room Entry",
    (-5, -2): "Before the Crash - Room Entry",
    (-5, -1): "Hold On Tight and Don't Look Down - Room Entry",
    (-5, 0): "Hydra Is Myth - Room Entry",
    (-5, 1): "Artisan Stone Walls - Room Entry",
    (-5, 2): "Cave In - Room Entry",
    (-5, 3): "Obvious Movie Quote - Room Entry",
    (-5, 4): "A Dream of a Memory - Room Entry",
    (-5, 5): "Mine Shaft - Room Entry",
    (-5, 6): "Forgotten Tunnels - Room Entry",

    (-4, -3): "This Is Where We Used to Live - Room Entry",
    (-4, -2): "A Brief Respite - Room Entry",
    (-4, -1): "The Coin and the Courage - Room Entry",
    (-4, 0): "Arcane Vocabulary - Room Entry",
    (-4, 1): "Venn's Banality - Room Entry",
    (-4, 2): "Crawlspace - Room Entry",
    (-4, 3): "Don't Be Hasty - Room Entry",
    (-4, 4): "A Memory of a Dream - Room Entry",
    (-4, 5): "Green Man - Room Entry",
    (-4, 6): "Descent - Room Entry",

    (-3, -3): "Catharsis in Catastrophe - Room Entry",
    (-3, -2): "Hardcore Prawn - Room Entry",
    (-3, -1): "Exit Strategy - Room Entry",
    (-3, 0): "You Have to Start the Game - Room Entry",
    (-3, 1): "Hops and Skips - Room Entry",
    (-3, 2): "Never Could See Any Other Way - Room Entry",
    (-3, 3): "You Definitely Shouldn't Go Left - Room Entry",
    (-3, 4): "Rawr! - Room Entry",
    (-3, 5): "Springheel Boots - Room Entry",
    (-3, 6): "The Arbitrarium - Room Entry",

    (-2, -3): "Linchpin - Room Entry",
    (-2, -2): "Point of No Return - Room Entry",
    (-2, -1): "Playing with Fire - Room Entry",
    (-2, 0): "KISS Principle - Room Entry",
    (-2, 1): "Leaps and Bounds - Room Entry",
    (-2, 2): "Pit of Spikes - Room Entry",
    (-2, 3): "Tower of Sorrows - Room Entry",
    (-2, 4): "Tower of Regrets - Room Entry",
    (-2, 5): "Back to the Surface - Room Entry",

    (-1, -4): "dynamic_room_left - Room Entry",
    (-1, -3): "Speak Now... - Room Entry",
    (-1, -2): "Open Sesame - Room Entry",
    (-1, -1): "From Another World - Room Entry",
    (-1, 0): "Snake, It's a Snake - Room Entry",
    (-1, 1): "Swimming Upstream - Room Entry",
    (-1, 2): "Subterranea - Room Entry",
    (-1, 3): "Contrived Lock/Key Mechanisms - Room Entry",
    (-1, 4): "Falling Into a Greener Life - Room Entry",

    (0, -4): "dynamic_room_right - Room Entry",
    (0, -3): "Consolation Prize - Room Entry",
    (0, -2): "Eponymous - Room Entry",
    (0, -1): "Harbinger - Room Entry",
    (0, 0): "Treasure Hunt - Room Entry",
    (0, 1): "Abstract Bridge - Room Entry",
    (0, 2): "Which Path Will I Take? - Room Entry",
    (0, 3): "Bat Cave - Room Entry",
    (0, 4): "Euclid Shrugged - Room Entry",

    (1, -1): "Taking the Long Way - Room Entry",
    (1, 0): "Danger - Room Entry",
    (1, 1): "Not All Those Who Wander Are Lost - Room Entry",
    (1, 2): "Cognitive Resonance - Room Entry",
    (1, 3): "Functional Spelaeology - Room Entry",
    (1, 4): "Circular Logic - Room Entry",

    (2, 0): "Leap of Faith - Room Entry",
    (2, 1): "Stick the Landing - Room Entry",
    (2, 2): "Precarious Footholds - Room Entry",
    (2, 3): "Fungal Forest - Room Entry",
    (2, 4): "Prawn Shot First - Room Entry",

    (3, 0): "On the Count of Three - Room Entry",
    (3, 1): "Mushroom Staircase - Room Entry",
    (3, 2): "Transplants - Room Entry",
    (3, 3): "The Proper Motivation - Room Entry",
    (3, 4): "Fish Out of Water - Room Entry",
    (3, 5): "Abandoned Alcove - Room Entry",
    (3, 6): "yeah but why u jelly tho - Room Entry",

    (4, 0): "Does Whatever A Spider Does - Room Entry",
    (4, 1): "Eden Maw - Room Entry",
    (4, 2): "Under Construction - Room Entry",
    (4, 3): "Remnants of a Past Unknown - Room Entry",
    (4, 4): "Castle Rock - Room Entry",
    (4, 5): "Observation Deck - Room Entry",
    (4, 6): "Wellspring - Room Entry",

    (5, 0): "Attic Storeroom - Room Entry",
    (5, 1): "Vestibule - Room Entry",
    (5, 2): "Shelter from the Storm - Room Entry",
    (5, 3): "Ghosts - Room Entry",
    (5, 4): "Uncertain Semiotics - Room Entry",
    (5, 5): "Don't Get Snippy With Me - Room Entry",
    (5, 6): "Crimson Aura - Room Entry",

    (6, 0): "Clarity Comes in Waves - Room Entry",
    (6, 1): "Great Hall - Room Entry",
    (6, 2): "Cave Painting - Room Entry",
    (6, 3): "The Loneliest Corner - Room Entry",
    (6, 4): "Rough Landing - Room Entry",
    (6, 5): "Bring a Mallet - Room Entry",
    (6, 6): "Dire Crab - Room Entry",

    (7, -1): "An Even 0x80 - Room Entry",
    (7, 0): "The Floor Is Lava - Room Entry",
    (7, 1): "Hollow King Transformed - Room Entry",
    (7, 2): "Worth It? - Room Entry",
    (7, 3): "Secret Cat Level - Room Entry",
    (7, 4): "Feline Foreshadowing - Room Entry",

    (8, 0): "Brazen Machines - Room Entry",
    (8, 1): "Spider Gloves - Room Entry",
    (8, 2): "Not Worth It! - Room Entry",
}